name: 📨 Deploy to Firebase App Distribution
on:  
  push:
    branches: [ main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: Android-CI-CD
        
      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: Android-CI-CD/app-debug.apk
